# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: openFPGA Cores Inventory
author:
  name: Joshua Campbell
  email:
description: > # this means to ignore newlines until "show_excerpts:"
  This site was created to document openFPGA cores and their related devices.

domain: openfpga-cores-inventory.github.io
baseurl: "/analogue-pocket" # the subpath of your site, e.g. /blog
url: https://openfpga-cores-inventory.github.io # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: false # set to true to show excerpts on the homepage

# Bootstrap date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
bootstrap:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # - { platform: devto,          title: "DEV",             user_url: "https://dev.to/jekyll" }
    # - { platform: dribbble,       title: "Dribbble",        user_url: "https://dribbble.com/jekyll" }
    # - { platform: facebook,       title: "Facebook",        user_url: "https://www.facebook.com/jekyll" }
    # - { platform: flickr,         title: "Flickr",          user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         title: "GitHub",          user_url: "https://github.com/openfpga-cores-inventory/analogue-pocket" }
    # - { platform: google_scholar, title: "Google Scholar",  user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    # - { platform: instagram,      title: "Instagram",       user_url: "https://www.instagram.com/jekyll" }
    # - { platform: keybase,        title: "Keybase",         user_url: "https://keybase.io/jekyll" }
    # - { platform: linkedin,       title: "LinkedIn",        user_url: "https://www.linkedin.com/in/jekyll" }
    # - { platform: microdotblog,   title: "Micro.blog",      user_url: "https://micro.blog/jekyll" }
    # - { platform: pinterest,      title: "Pinterest",       user_url: "https://www.pinterest.com/jekyll" }
    # - { platform: rss,            title: "RSS",             user_url: "/feed.xml" }
    # - { platform: stackoverflow,  title: "Stack Overflow",  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
    # - { platform: telegram,       title: "Telegram",        user_url: "https://t.me/jekyll" }
    - { platform: twitter,        title: "Twitter",         user_url: "https://twitter.com/joshcampbell191" }
    # - { platform: youtube,        title: "YouTube",         user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - index.md

# Build settings
remote_theme: joshcampbell191/jekyll-theme-bootstrap

plugins:
 - jekyll-feed
 - jekyll-seo-tag
