- repository: agg23/fpga-gameandwatch
  assets:
    - agg23.GameAndWatch_.*-Pocket
- repository: agg23/fpga-tamagotchi
  assets:
    - agg23.Tamagotchi_.*-Pocket
- repository: agg23/openfpga-arduboy
- repository: agg23/openfpga-pong
- repository: agg23/openfpga-pcengine
- repository: agg23/openfpga-pokemonmini
- repository: agg23/openfpga-wonderswan
- repository: agg23/openfpga-nes
- repository: agg23/openfpga-snes
- repository: antongale/arcade-exerion
- repository: antongale/arcade-performan
- repository: antongale/arcade-slapfight
- repository: antongale/arcade-taitosj
- repository: awesomedolphin/openfpga-spaceinvaders
  assets:
    - AwesomeDolphin.SpaceInvaders_
- repository: budude2/openfpga-atarilynx
- repository: budude2/openfpga-gbc
  assets:
    - openfpga-gb-
    - openfpga-gbc-
- repository: coin-opcollection/distribution-openfpga
  contents:
    - Releases/atrac17.combatribes.zip
    - Releases/atrac17.pipibibs.zip
    - Releases/atrac17.tekipaki.zip
    - Releases/atrac17.truxton2.zip
    - Releases/pram0d.bakraid.zip
    - Releases/pram0d.batrider.zip
    - Releases/pram0d.doubledragoniii.zip
    - Releases/pram0d.garegga.zip
    - Releases/pram0d.snowbros2.zip
    - Releases/pram0d.wrestlefest.zip
    - Releases/pram0d.yunit.zip
    - Releases/pram0d.zunit.zip
- repository: dave18/memtest_pocket
- repository: dave18/openfpga_zx-spectrum
- repository: ericlewis/openfpga-asteroids
- repository: ericlewis/openfpga-dominos
- repository: ericlewis/openfpga-donkeykong
- repository: ericlewis/openfpga-lunarlander
- repository: ericlewis/openfpga-spacerace
- repository: ericlewis/openfpga-superbreakout
- repository: ericlewis/openfpga-qbert
- repository: ericlewis/openfpga-radarscope
- repository: jotego/jtbin
  contents:
    - pocket/zips/jotego.jt1942.zip
    - pocket/zips/jotego.jt1943.zip
    - pocket/zips/jotego.jtaliens.zip
    - pocket/zips/jotego.jtbiocom.zip
    - pocket/zips/jotego.jtbtiger.zip
    - pocket/zips/jotego.jtbubl.zip
    - pocket/zips/jotego.jtcastle.zip
    - pocket/zips/jotego.jtcircus.zip
    - pocket/zips/jotego.jtcommnd.zip
    - pocket/zips/jotego.jtcomsc.zip
    - pocket/zips/jotego.jtcontra.zip
    - pocket/zips/jotego.jtcop.zip
    - pocket/zips/jotego.jtcps1.zip
    - pocket/zips/jotego.jtcps15.zip
    - pocket/zips/jotego.jtcps2.zip
    - pocket/zips/jotego.jtdd.zip
    - pocket/zips/jotego.jtdd2.zip
    - pocket/zips/jotego.jtexed.zip
    - pocket/zips/jotego.jtflane.zip
    - pocket/zips/jotego.jtflstory.zip
    - pocket/zips/jotego.jtfround.zip
    - pocket/zips/jotego.jtgaiden.zip
    - pocket/zips/jotego.jtgng.zip
    - pocket/zips/jotego.jtgunsmk.zip
    - pocket/zips/jotego.jtkarnov.zip
    - pocket/zips/jotego.jtkchamp.zip
    - pocket/zips/jotego.jtkicker.zip
    - pocket/zips/jotego.jtkiwi.zip
    - pocket/zips/jotego.jtkunio.zip
    - pocket/zips/jotego.jtlabrun.zip
    - pocket/zips/jotego.jtmidres.zip
    - pocket/zips/jotego.jtmikie.zip
    - pocket/zips/jotego.jtmx5k.zip
    - pocket/zips/jotego.jtngp.zip
    - pocket/zips/jotego.jtngpc.zip
    - pocket/zips/jotego.jtninja.zip
    - pocket/zips/jotego.jtoutrun.zip
    - pocket/zips/jotego.jtpang.zip
    - pocket/zips/jotego.jtparoda.zip
    - pocket/zips/jotego.jtpinpon.zip
    - pocket/zips/jotego.jtrastan.zip
    - pocket/zips/jotego.jtriders.zip
    - pocket/zips/jotego.jtroadf.zip
    - pocket/zips/jotego.jtroc.zip
    - pocket/zips/jotego.jtrumble.zip
    - pocket/zips/jotego.jts16.zip
    - pocket/zips/jotego.jts16b.zip
    - pocket/zips/jotego.jts18.zip
    - pocket/zips/jotego.jtsarms.zip
    - pocket/zips/jotego.jtsbaskt.zip
    - pocket/zips/jotego.jtsectnz.zip
    - pocket/zips/jotego.jtsf.zip
    - pocket/zips/jotego.jtshanon.zip
    - pocket/zips/jotego.jtshouse.zip
    - pocket/zips/jotego.jtsimson.zip
    - pocket/zips/jotego.jtslyspy.zip
    - pocket/zips/jotego.jttmnt.zip
    - pocket/zips/jotego.jttoki.zip
    - pocket/zips/jotego.jttora.zip
    - pocket/zips/jotego.jttrack.zip
    - pocket/zips/jotego.jttrojan.zip
    - pocket/zips/jotego.jttwin16.zip
    - pocket/zips/jotego.jtvigil.zip
    - pocket/zips/jotego.jtwc.zip
    - pocket/zips/jotego.jtwwfss.zip
    - pocket/zips/jotego.jtxmen.zip
    - pocket/zips/jotego.jtyiear.zip
    - pocket/zips/jotego.jtthundr.zip
- repository: markus-zzz/myc64-pocket
- repository: mazamars312/analogue-amiga
- repository: mazamars312/analogue_pocket_neogeo
- repository: mazamars312/openfpga-pcengine-cd
- repository: nullobject/openfpga-tecmo
- repository: obsidian-dot-dev/openfpga-asteroidsdeluxe
- repository: obsidian-dot-dev/openfpga-atarisystem1
- repository: obsidian-dot-dev/openfpga-bagman
- repository: obsidian-dot-dev/openfpga-defender
- repository: obsidian-dot-dev/openfpga-donkeykong3
- repository: obsidian-dot-dev/openfpga-donkeykongjunior
- repository: obsidian-dot-dev/openfpga-druaga
- repository: obsidian-dot-dev/openfpga-gaplus
- repository: obsidian-dot-dev/openfpga-gauntlet
- repository: obsidian-dot-dev/openfpga-gyruss
- repository: obsidian-dot-dev/openfpga-joust2
- repository: obsidian-dot-dev/openfpga-mariobros
- repository: obsidian-dot-dev/openfpga-robotron
- repository: obsidian-dot-dev/openfpga-vectrex
- repository: opengateware/arcade-bankp
- repository: opengateware/arcade-congo
- repository: opengateware/arcade-digdug
- repository: opengateware/arcade-galaga
- repository: opengateware/arcade-gberet
- repository: opengateware/arcade-irem_m92
  assets:
    - opengateware.irem_m92_.*-pocket
- repository: opengateware/arcade-pooyan
- repository: opengateware/arcade-xevious
- repository: opengateware/computer-msx
- repository: opengateware/console-supervision
- repository: opengateware/openfpga-genesis
- repository: rndmnkiii/arcade-irem_m92_analogizer
- repository: rndmnkiii/analogizer-amiga
- repository: rndmnkiii/analogizer-openfpga-atarilynx
- repository: rndmnkiii/analogizer-openfpga-atarisystem1
- repository: rndmnkiii/analogizer-pocket-alpha-mission
- repository: rndmnkiii/analogizer_arcade-slapfight
- repository: rndmnkiii/analogizer_mazamars312_neogeo_0.8.1
- repository: rndmnkiii/analogizer_openfpga-tecmo
- repository: rndmnkiii/analogizer_openfpga-gbc
  assets:
    - analogizer-openfpga-gb-
    - analogizer-openfpga-gbc-
- repository: rndmnkiii/analogizer_openfpga-gauntlet
- repository: rndmnkiii/analogizer_openfpga-genesis
- repository: rndmnkiii/analogizer_openfpga-pcengine
- repository: rndmnkiii/openfpga-nes-analogizer
- repository: rndmnkiii/openfpga-pcengine-cd_analogizer
- repository: rndmnkiii/openfpga-snes-analogizer
- repository: rndmnkiii/pocketalphamission
  assets:
    - rndmnkiii.alphamission_pocket-
- repository: rolandking/openfpga-athena
- repository: rolandking/openfpga-jailbreak
- repository: somhi/flappybird
- repository: spacemen3/pdp-1
- repository: spiritualized1997/openfpga-2600
- repository: spiritualized1997/openfpga-7800
- repository: spiritualized1997/openfpga-adventure-vision
- repository: spiritualized1997/openfpga-arcadia
- repository: spiritualized1997/openfpga-channel-f
- repository: spiritualized1997/openfpga-coleco
- repository: spiritualized1997/openfpga-creativision
- repository: spiritualized1997/openfpga-gamate
- repository: spiritualized1997/openfpga-game-king
- repository: spiritualized1997/openfpga-genesis
- repository: spiritualized1997/openfpga-gb-gbc
  assets:
    - Spiritualized_GB_
    - Spiritualized_GBC_
- repository: spiritualized1997/openfpga-gba
- repository: spiritualized1997/openfpga-gg
- repository: spiritualized1997/openfpga-intellivision
- repository: spiritualized1997/openfpga-megaduck
- repository: spiritualized1997/openfpga-nes
- repository: spiritualized1997/openfpga-odyssey-2
- repository: spiritualized1997/openfpga-studio-2
- repository: spiritualized1997/openfpga-super-gb
- repository: spiritualized1997/openfpga-supervision
- repository: spiritualized1997/openfpga-sg1000
- repository: spiritualized1997/openfpga-sms
- repository: spiritualized1997/openfpga-videobrain
- repository: tsalvo/openfpga-varvara
- repository: opengateware/arcade-irem_m72
  assets:
    - boogermann.irem_m72_.*-pocket
