- username: agg23
  cores:
    - repository: openfpga-arduboy
    - repository: openfpga-pong
    - repository: openfpga-NES
    - repository: openfpga-pcengine
    - repository: openfpga-pokemonmini
    - repository: openfpga-SNES
    - repository: fpga-tamagotchi
      filter: agg23.Tamagotchi_.*-Pocket
    - repository: openfpga-wonderswan
    - repository: fpga-gameandwatch
      filter: agg23.GameAndWatch_.*-Pocket
- username: antongale
  cores:
    - repository: arcade-exerion
    - repository: arcade-performan
    - repository: arcade-slapfight
    - repository: arcade-taitosj
- username: AwesomeDolphin
  cores:
    - repository: openFPGA-SpaceInvaders
      filter: AwesomeDolphin.SpaceInvaders_
- username: budude2
  cores:
    - repository: openfpga-GBC
      filter: openfpga-gbc-
    - repository: openfpga-GBC
      filter: openfpga-gb-
- username: Coin-OpCollection
  cores:
    - repository: Distribution-OpenFPGA
      path: Releases/pram0d.batrider_20221218.zip
    - repository: Distribution-OpenFPGA
      path: Releases/pram0d.bakraid_20221218.zip
    - repository: Distribution-OpenFPGA
      path: Releases/pram0d.garegga_20221030.zip
    - repository: Distribution-OpenFPGA
      path: Releases/pram0d.snowbros2_20221019.zip
    - repository: Distribution-OpenFPGA
      path: Releases/atrac17.tekipaki_20240518.zip
    - repository: Distribution-OpenFPGA
      path: Releases/atrac17.truxton2_20240518.zip
    - repository: Distribution-OpenFPGA
      path: Releases/atrac17.pipibibs_20240518.zip
- username: ericlewis
  cores:
    - repository: openfpga-asteroids
    - repository: openfpga-dominos
      prerelease: true
    - repository: openFPGA-DonkeyKong
      prerelease: true
    - repository: openfpga-lunarlander
      prerelease: true
    - repository: openfpga-qbert
    - repository: openFPGA-RadarScope
      prerelease: true
    - repository: openfpga-spacerace
    - repository: openfpga-superbreakout
      prerelease: true
- username: jotego
  cores:
    - repository: jtbin
      path: pocket/zips/jotego.jtcontra.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtcps1.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtdd.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtdd2.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtexed.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtgng.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtgunsmk.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtkarnov.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtkicker.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtkunio.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtmikie.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtoutrun.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtpang.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtpinpon.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtroadf.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtcop.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtroc.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtsectnz.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtsarms.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtsf.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtsbaskt.zip
    - repository: jtbin
      path: pocket/zips/jotego.jttrack.zip
    - repository: jtbin
      path: pocket/zips/jotego.jttrojan.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtvigil.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtyiear.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtcomsc.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtkiwi.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtcastle.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtrastan.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtbtiger.zip
    - repository: jtbin
      path: pocket/zips/jotego.jttmnt.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtaliens.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtsimson.zip
    - repository: jtbin
      path: pocket/zips/jotego.jts16b.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtfround.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtshanon.zip
    - repository: jtbin
      path: pocket/zips/jotego.jttora.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtninja.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtcps2.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtcps15.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtbubl.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtshouse.zip
    - repository: jtbin
      path: pocket/zips/jotego.jts16.zip
    - repository: jtbin
      path: pocket/zips/jotego.jt1942.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtngp.zip
    - repository: jtbin
      path: pocket/zips/jotego.jt1943.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtmx5k.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtkchamp.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtcommnd.zip
    - repository: jtbin
      path: pocket/zips/jotego.jttoki.zip
    - repository: jtbin
      path: pocket/zips/jotego.jts18.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtbiocom.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtslyspy.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtflane.zip
    - repository: jtbin
      path: pocket/zips/jotego.jtriders.zip
- username: markus-zzz
  cores:
    - repository: myc64-pocket
- username: Mazamars312
  cores:
    - repository: Analogue-Amiga
    - repository: Analogue_Pocket_Neogeo
    - repository: openfpga-pcengine-cd
- username: nullobject
  cores:
    - repository: openfpga-tecmo
- username: obsidian-dot-dev
  cores:
    - repository: openFPGA-asteroidsdeluxe
    - repository: openFPGA-DonkeyKong3
    - repository: openFPGA-DonkeyKongJunior
    - repository: openFPGA-MarioBros
    - repository: openFPGA-Druaga
    - repository: openFPGA-Vectrex
    - repository: openFPGA-Defender
    - repository: openFPGA-Robotron
    - repository: openFPGA-Gaplus
    - repository: openFPGA-Joust2
    - repository: openFPGA-Gauntlet
    - repository: openFPGA-AtariSystem1
- username: opengateware
  cores:
    - repository: arcade-bankp
    - repository: arcade-congo
    - repository: arcade-digdug
    - repository: arcade-galaga
    - repository: openfpga-genesis
      prerelease: true
    - repository: arcade-gberet
    - repository: arcade-pooyan
    - repository: console-supervision
    - repository: arcade-xevious
    - repository: arcade-irem_m92
      filter: opengateware.irem_m92_.*-pocket
- username: RndMnkIII
  cores:
    - repository: PocketAlphaMission
    - repository: Analogizer_Mazamars312_Neogeo_0.8.1
    - repository: Analogizer-Pocket-Alpha-Mission
    - repository: openfpga-NES-Analogizer
    - repository: openfpga-SNES-Analogizer
    - repository: Analogizer_openfpga-pcengine
    - repository: openfpga-pcengine-cd_Analogizer
    - repository: arcade-irem_m92_Analogizer
    - repository: Analogizer_openFPGA-Gauntlet
    - repository: Analogizer_openFPGA-Genesis
    - repository: Analogizer-openFPGA-AtariSystem1
- username: rolandking
  cores:
    - repository: openFPGA-jailbreak
    - cores: null
      repository: openFPGA-Athena
- username: somhi
  cores:
    - repository: FlappyBird
- username: spacemen3
  cores:
    - repository: PDP-1
- username: spiritualized1997
  cores:
    - repository: openFPGA-Adventure-Vision
    - repository: openFPGA-Arcadia
    - repository: openFPGA-2600
    - repository: openFPGA-7800
    - repository: openFPGA-Channel-F
    - repository: openFPGA-Coleco
    - repository: openFPGA-Creativision
    - repository: openFPGA-Gamate
    - repository: openFPGA-Game-King
    - repository: openFPGA-GB-GBC
      filter: Spiritualized_GB_
    - repository: openFPGA-GBA
    - repository: openFPGA-GB-GBC
      filter: Spiritualized_GBC_
    - repository: openFPGA-Genesis
    - repository: openFPGA-Intellivision
    - repository: openFPGA-Megaduck
    - repository: openFPGA-NES
    - repository: openFPGA-Odyssey-2
    - repository: openFPGA-GG
    - repository: openFPGA-SMS
    - repository: openFPGA-SG1000
    - repository: openFPGA-Studio-2
    - repository: openFPGA-Supervision
    - repository: openFPGA-Super-GB
    - repository: openFPGA-VideoBrain
- username: tsalvo
  cores:
    - repository: openfpga-varvara
